name: Build Mac DMG

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Mac App
      run: pyinstaller --windowed --name "IMERP" app.py

    - name: Create DMG File
      run: hdiutil create -volname "IMERP" -srcfolder dist/IMERP.app -ov -format UDZO IMERP.dmg

    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: IMERP-Mac-Installer
        path: IMERP.dmg